name: flutter_firebase_chat_core
description: >
  Actively maintained, community-driven Firebase BaaS for chat applications
  with an optional chat UI.
version: 1.6.4
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_firebase_chat_core

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  cloud_firestore: ^4.0.3
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.0
  meta: ^1.8.0

dev_dependencies:
  dart_code_metrics: ^4.21.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
